Description: Exercise for create Infrastructure

Parameters:
  InstanceType:
    Description: Type for the instance
    Type: String

  IDOfAMI:
    Description: AMI id for the instance
    Type: String

  KeyPair:
    Description: key pair for shh connect
    Type: String

Resourses:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: !Ref KeyPair
      ImageId: !Ref IDOfAMI
      InstanceType: !Ref InstanceType
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
