version: 2.1
workflows:
  CreateInfra:
    jobs:
      - createInfra

jobs:
  createInfra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: add credentials to give access for aws account
          command: json| aws configure | $AWS_ACCESS_KEY_ID | $AWS_SECRET_KEY | us-east-1

      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation create-stack \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
            --template-body file://infr.yml \
            --parameters file://infr-params.json
